apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginxfrontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginxserver
        image: nginx
        ports:
          - name: nginxwebport
            containerPort: 80
            protocol: TCP